### ISSUE TITLE
Sergey Kachalkov, [09.11.17 16:48] думаю есть смысл на слово амиго придумать триггеры.

### ISSUE THREAD

**Issue by ilya-bin** [ilya-bin/epic-bot#2]
и на мучачо добавить их в один словарь

**Comment by pelodka** [comment]
Раздел Собутыльник Артема.
Триггеры: амиго, мучач, кисел, христиан, библия, библию, ветхий, свято, канонизи, канониза, священн, иуде, иудаи, правосла, сири

Комменты:
Пойдём покурим.
Но это не точно.
Как боженька ща сказал.
Ну, за то, чтобы не было войны!
Верните мне мой 1993 год.
Кстати, в космосе мы тоже всех уделали.
Встаём с колен, это правда!

**Comment by ilya-bin** [comment]
@pelodka мне кажется библию и эту тему в отдельный раздел религий надо

**Comment by pelodka** [comment]
@ilya-bin Ну можно, я чот увлёкся

**Comment by ilya-bin** [comment]
Закрываю
