### ISSUE TITLE
антона просьба

### ISSUE THREAD

**Issue by ilya-bin** [ilya-bin/epic-bot#3]
Добавь такую фразу:
Нахуй тебя и нахуй пыню
Со своим послушной толпой
Лучше я сдохну ебучим нонеймом
Чем прославлюсь и стану тобой     (реакция на либер\либераст)

**Comment by pelodka** [comment]
Исправленный текст
_Нахуй тебя и нахуй пыню
Со сво**ей** послушной толпой
Лучше я сдохну ебучим нонеймом
Чем прославлюсь и стану тобой_

**Comment by pelodka** [comment]
#4 починено тут, можно закрывать
