### ISSUE TITLE
Расширение словаря - work

### ISSUE THREAD

**Issue by pelodka** [ilya-bin/epic-bot#8]
- раздел политота: добавить сталина, трампа, обаму в триггеры. Добавить пару ответов.
- новый раздел: работа. Триггеры: Аджит, Кумар, релиз, бондаренк, вася, сильман, хабарин и тп. Придумать остроумные ответы.

**Comment by ilya-bin** [comment]
@pelodka можно прям отсюда комментить круто

**Comment by pelodka** [comment]
@ilya-bin Идеи для раздела Работа. Комменты: Арбайт махт фрай. Труд сделает тебя свободным. Пацаны, когда бухать пойдём? А может быть забудем все и сбежим

**Comment by pelodka** [comment]
Раздел Работа, комменты:
Да хорош, давай по пивку!
Лень сделает тебя рабом!
Соблюдай корпоративный этикет, умник.
Почту проверь!
У тебя там билд упал, кстати.

**Comment by ilya-bin** [comment]
@pelodka слова триггеры Сильман, Аджит, индус, спеки

**Comment by ilya-bin** [comment]
раздел менты
